apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: hyperscale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: ghcr.io/meghana660/hyperscale-cart-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: hyperscale
spec:
  selector:
    app: cart-service
  ports:
    - port: 8000
      targetPort: 8000
