apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: hyperscale
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ghcr.io/meghana660/hyperscale-product-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: PRODUCT_DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/hyperscale
            - name: MONGO_URI
              value: mongodb://mongodb:27017
            - name: REDIS_HOST
              value: redis
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: hyperscale
spec:
  selector:
    app: product-service
  ports:
    - port: 8000
      targetPort: 8000
